
const routes = [
  {
    path: "/",
    component: () => import("layouts/MainLayout.vue"),
    children: [
      { path: "", component: () => import("pages/Index.vue") },
      { path: "/bi", component: () => import("pages/BI.vue") },
      { path: "/lmgss", component: () => import("pages/LMGSS.vue") },
      { path: "/tgig", component: () => import("pages/TGIG.vue") },
      { path: "/hosts", component: () => import("pages/Hosts.vue") },
      { path: "/formerhosts", component: () => import("pages/FormerHosts.vue") },
      { path: "/privacy", component: () => import("pages/Privacy.vue") },
      { path: "/terms", component: () => import("pages/Terms.vue") },
      { path: "/question", component: () => import("pages/Question.vue") },
      { path: "/contact", component: () => import("pages/Contact.vue") },
      { path: "/contacted", component: () => import("pages/Contacted.vue") },
      { path: "/links", component: () => import("pages/Links.vue") },
      { path: "/schedule", component: () => import("pages/Schedule.vue") },
      { path: "/moneygame", component: () => import("pages/MoneyGame.vue") },
      { path: "/highvibeliving", component: () => import("pages/HighVibeLiving.vue") },
      { path: "/streammeditation", component: () => import("pages/StreamMeditation.vue") },

      // Real Success Stories Of The Law Of Attraction E-book
      { path: "/rssotloa/toc", component: () => import("pages/rssotloa/toc.vue") },
      { path: "/rssotloa/introduction", component: () => import("pages/rssotloa/introduction.vue") },
      { path: "/rssotloa/homeSweetHome", component: () => import("pages/rssotloa/homeSweetHome.vue") },
      { path: "/rssotloa/theLot", component: () => import("pages/rssotloa/theLot.vue") },
      { path: "/rssotloa/manifestingAnApartmentOnCentralParkWest", component: () => import("pages/rssotloa/manifestingAnApartmentOnCentralParkWest.vue") },
      { path: "/rssotloa/ourDreamHouseInNorthernCalifornia", component: () => import("pages/rssotloa/ourDreamHouseInNorthernCalifornia.vue") },
      { path: "/rssotloa/divorcedBrokeAndHomeless", component: () => import("pages/rssotloa/divorcedBrokeAndHomeless.vue") },
      { path: "/rssotloa/wouldntItBeCoolToLiveHere", component: () => import("pages/rssotloa/wouldntItBeCoolToLiveHere.vue") },
      { path: "/rssotloa/arizonaDreaming", component: () => import("pages/rssotloa/arizonaDreaming.vue") },
      { path: "/rssotloa/aNewHealingCenter", component: () => import("pages/rssotloa/aNewHealingCenter.vue") },
      { path: "/rssotloa/trapped", component: () => import("pages/rssotloa/trapped.vue") },
      { path: "/rssotloa/ourDreamHome", component: () => import("pages/rssotloa/ourDreamHome.vue") },
      { path: "/rssotloa/treasuresFromTikashi", component: () => import("pages/rssotloa/treasuresFromTikashi.vue") },
      { path: "/rssotloa/beginningAgain", component: () => import("pages/rssotloa/beginningAgain.vue") },
      { path: "/rssotloa/signsFromTheUniverse", component: () => import("pages/rssotloa/signsFromTheUniverse.vue") },
      { path: "/rssotloa/theSellerWhoWasTheBuyersAlly", component: () => import("pages/rssotloa/theSellerWhoWasTheBuyersAlly.vue") },
      { path: "/rssotloa/aFinancialSurprise", component: () => import("pages/rssotloa/aFinancialSurprise.vue") },
      { path: "/rssotloa/sailing", component: () => import("pages/rssotloa/sailing.vue") },
      { path: "/rssotloa/itsNoAccident", component: () => import("pages/rssotloa/itsNoAccident.vue") },
      { path: "/rssotloa/makingChanges", component: () => import("pages/rssotloa/makingChanges.vue") },
      { path: "/rssotloa/londonCalling", component: () => import("pages/rssotloa/londonCalling.vue") },
      { path: "/rssotloa/gettingPublished", component: () => import("pages/rssotloa/gettingPublished.vue") },
      { path: "/rssotloa/thePokerTournament", component: () => import("pages/rssotloa/thePokerTournament.vue") },
      { path: "/rssotloa/healingMyself", component: () => import("pages/rssotloa/healingMyself.vue") },
      { path: "/rssotloa/bootCamp", component: () => import("pages/rssotloa/bootCamp.vue") },
      { path: "/rssotloa/nizhoni", component: () => import("pages/rssotloa/nizhoni.vue") },
      { path: "/rssotloa/copingWithArthritis", component: () => import("pages/rssotloa/copingWithArthritis.vue") },
      { path: "/rssotloa/allIsWell", component: () => import("pages/rssotloa/allIsWell.vue") },
      { path: "/rssotloa/theBoyfriend", component: () => import("pages/rssotloa/theBoyfriend.vue") },
      { path: "/rssotloa/fireAlarmsToWeddingBells", component: () => import("pages/rssotloa/fireAlarmsToWeddingBells.vue") },
      { path: "/rssotloa/welcomingANewChild", component: () => import("pages/rssotloa/welcomingANewChild.vue") },
      { path: "/rssotloa/manOfMyDreams", component: () => import("pages/rssotloa/manOfMyDreams.vue") },
      { path: "/rssotloa/markus", component: () => import("pages/rssotloa/markus.vue") },
      { path: "/rssotloa/beingFound", component: () => import("pages/rssotloa/beingFound.vue") },
      { path: "/rssotloa/friendsDeliveredToMeByTheLawOfAttraction", component: () => import("pages/rssotloa/friendsDeliveredToMeByTheLawOfAttraction.vue") },
      { path: "/rssotloa/overcomingFiveDevastatingLosses", component: () => import("pages/rssotloa/overcomingFiveDevastatingLosses.vue") },
      { path: "/rssotloa/theBathThatKeepsOnGifting", component: () => import("pages/rssotloa/theBathThatKeepsOnGifting.vue") },
      { path: "/rssotloa/theThirdDegree", component: () => import("pages/rssotloa/theThirdDegree.vue") },
      { path: "/rssotloa/hideAndSeek", component: () => import("pages/rssotloa/hideAndSeek.vue") },
      { path: "/rssotloa/outOfTheDarkness", component: () => import("pages/rssotloa/outOfTheDarkness.vue") },
      { path: "/rssotloa/anybodyButMe", component: () => import("pages/rssotloa/anybodyButMe.vue") },
      { path: "/rssotloa/theOnlyChoice", component: () => import("pages/rssotloa/theOnlyChoice.vue") },
      { path: "/rssotloa/myBoatWasTakingOnWater", component: () => import("pages/rssotloa/myBoatWasTakingOnWater.vue") },
      { path: "/rssotloa/viennaStation", component: () => import("pages/rssotloa/viennaStation.vue") },
      { path: "/rssotloa/aSteinwayPiano", component: () => import("pages/rssotloa/aSteinwayPiano.vue") },
      { path: "/rssotloa/illHaveAnOwlPlease", component: () => import("pages/rssotloa/illHaveAnOwlPlease.vue") },
      { path: "/rssotloa/finsUp", component: () => import("pages/rssotloa/finsUp.vue") },
      { path: "/rssotloa/hurricaneFloyd", component: () => import("pages/rssotloa/hurricaneFloyd.vue") },
      { path: "/rssotloa/alteringTheWeather", component: () => import("pages/rssotloa/alteringTheWeather.vue") },
      { path: "/rssotloa/theMicroburst", component: () => import("pages/rssotloa/theMicroburst.vue") },
      { path: "/rssotloa/blueSkiesPlease", component: () => import("pages/rssotloa/blueSkiesPlease.vue") },
      { path: "/rssotloa/noMoreSnow", component: () => import("pages/rssotloa/noMoreSnow.vue") },
      { path: "/rssotloa/theJourneyAchievementWritingContests", component: () => import("pages/rssotloa/theJourneyAchievementWritingContests.vue") },
      { path: "/rssotloa/thePeoplesChoiceAwards", component: () => import("pages/rssotloa/thePeoplesChoiceAwards.vue") },
      { path: "/rssotloa/didISeeYouInACommercial", component: () => import("pages/rssotloa/didISeeYouInACommercial.vue") },
      { path: "/rssotloa/accidentIThinkNot", component: () => import("pages/rssotloa/accidentIThinkNot.vue") },
      { path: "/rssotloa/homesCatsAndCars", component: () => import("pages/rssotloa/homesCatsAndCars.vue") }
    ]
  }
];

// Always leave this as last one
routes.push({
  path: '*',
  component: () => import('pages/Error404.vue')
})

export default routes
